package com.xiyuan.demo.dao;

import com.xiyuan.demo.model.PayItem;

public interface PayItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_item
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_item
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    int insert(PayItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_item
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    int insertSelective(PayItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_item
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    PayItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_item
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    int updateByPrimaryKeySelective(PayItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_item
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    int updateByPrimaryKey(PayItem record);
}