package com.xiyuan.demo.model;

import java.util.Date;

public class PayItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.id
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.total_amount
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private Double totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.out_trade_no
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.trade_no
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.buyer_id
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private String buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.pay_type
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.pay_status
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.create_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.finish_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.close_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_item.remark
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.id
     *
     * @return the value of pay_item.id
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.id
     *
     * @param id the value for pay_item.id
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.total_amount
     *
     * @return the value of pay_item.total_amount
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public Double getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.total_amount
     *
     * @param totalAmount the value for pay_item.total_amount
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.out_trade_no
     *
     * @return the value of pay_item.out_trade_no
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.out_trade_no
     *
     * @param outTradeNo the value for pay_item.out_trade_no
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.trade_no
     *
     * @return the value of pay_item.trade_no
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.trade_no
     *
     * @param tradeNo the value for pay_item.trade_no
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.buyer_id
     *
     * @return the value of pay_item.buyer_id
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.buyer_id
     *
     * @param buyerId the value for pay_item.buyer_id
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.pay_type
     *
     * @return the value of pay_item.pay_type
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.pay_type
     *
     * @param payType the value for pay_item.pay_type
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.pay_status
     *
     * @return the value of pay_item.pay_status
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.pay_status
     *
     * @param payStatus the value for pay_item.pay_status
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.create_time
     *
     * @return the value of pay_item.create_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.create_time
     *
     * @param createTime the value for pay_item.create_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.finish_time
     *
     * @return the value of pay_item.finish_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.finish_time
     *
     * @param finishTime the value for pay_item.finish_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.close_time
     *
     * @return the value of pay_item.close_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.close_time
     *
     * @param closeTime the value for pay_item.close_time
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_item.remark
     *
     * @return the value of pay_item.remark
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_item.remark
     *
     * @param remark the value for pay_item.remark
     *
     * @mbggenerated Fri Sep 23 10:23:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}